# This ought to be filtered by branch (thus it's not named .build.yml *yet*)
image: debian/stable
packages:
  - libfuse-dev
  - pkgconf
sources:
  - https://git.sr.ht/~az1/iso9660-rs#rockridge
tasks:
  - setup: |
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --default-toolchain none
      source $HOME/.cargo/env
      rustup toolchain install nightly --profile minimal
  - build: |
      source $HOME/.cargo/env
      cd iso9660-rs
      cargo +nightly build
  - test: |
      source $HOME/.cargo/env
      cd iso9660-rs
      cargo +nightly test

