[package]
name = "iso9660"
version = "0.1.0"
authors = ["Ian Douglas Scott <ian@iandouglasscott.com>"]

[dependencies]
time = "0.1"
bitflags = "1.0"
nom = "4.0.0-beta2"

[dev-dependencies]
md5 = "0.3"
